### PR TITLE
Test package upload with bats

### PR DESCRIPTION
**Pull request by stbenjam**
Package uploading is broken (http://projects.theforeman.org/issues/12123).  Just adding a small test to BATS for it.

### CODE REVIEW

**Comment by ehelms** [comment]
ACK

**Comment by jlsherrill** [comment]
where does the animaniacs rpm come from?

**Comment by jlsherrill** [comment]
doh, i can't read

**Comment by stbenjam** [comment]
This will break the pipeline.  Fix: https://github.com/Katello/katello/pull/5526

**Pull request merged**
