### PR TITLE
use rpm to install epel release

### PR DESCRIPTION
**Pull request by jlsherrill**
as that is what foreman-bats does and they have not seen failures on installation

### CODE REVIEW

**Comment by ehelms** [comment]
Do you want to temporarily point systest_katello at your fork and branch of katello-deploy to see if this fixes the issue?

**Comment by jlsherrill** [comment]
@ehelms yeah i had contemplated that but figured i'd open the PR first, doing that now

**Comment by jlsherrill** [comment]
test run:  http://ci.theforeman.org/view/Katello%20Pipeline/job/systest_katello/1466/console

**Comment by jlsherrill** [comment]
@ehelms that was successful, which makes no sense, want me to try a 2nd time?

**Comment by ehelms** [comment]
Isn't the point to be successful since its using this PR?

**Comment by jlsherrill** [comment]
Yes that is the point, but it makes no sense :)

It actually passed once in the past ~3 weeks, so lets go with 'this fixes it'

**Comment by ehelms** [comment]
ACK

**Pull request merged**
