### PR TITLE
migrate travis builds from legacy to container-based

### PR DESCRIPTION
**Pull request by komidore64**
reference: https://docs.travis-ci.com/user/migrating-from-legacy

### CODE REVIEW

**Comment by ehelms** [comment]
ACK

**Comment by ekohl** [comment]
While you're at it: the ```bundle install``` line is redundant and can be removed.

**Comment by komidore64** [comment]
@ehelms, @ekohl update

**Comment by ekohl** [comment]
:+1:

**Comment by ekohl** [comment]
Forgot, it's ACK here.

**Comment by ehelms** [comment]
ACK

**Comment by komidore64** [comment]
i can't merge this

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
