### PR TITLE
Rename to Forklift

### PR DESCRIPTION
**Pull request by ehelms**
Based upon a survey done on foreman-dev, the project is being
renamed to Forklift to remove the katello specific nature.

### CODE REVIEW

**Comment by ehelms** [comment]
Opening up for comment based upon survey from foreman-dev

**Comment by stbenjam** [comment]
How about a logo?Haha https://openclipart.org/detail/203492/montacargas

**Comment by ehelms** [comment]
+1 to logo, however, that one is borderline creepy and cute ;)

**Comment by stbenjam** [comment]
I think it's definitely past the borderline of being creepy.

**Comment by stbenjam** [comment]
A couple of references to Katello deploy still in the README:


```
./README.md:    PROJECT_PATH = "#{KatelloDeploy::ROOT}/../a_repo"
./README.md:    KatelloDeploy.define_vm config, KatelloDeploy.new_box(PARENT_NAME, DB) do |machine|
./README.md:    KatelloDeploy.define_vm config, KatelloDeploy.new_box(PARENT_NAME, WEB) do |machine|
```

**Comment by ehelms** [comment]
Updated

**Comment by stbenjam** [comment]
Tested this and it all seems to be working right.  ACK from me

Any plugins such as downstream of course need updating, but it seemed as simple as `s/Katello Deploy/Forklift/` in the Vagrantfile

**Comment by daviddavis** [comment]
> How about a logo?Haha https://openclipart.org/detail/203492/montacargas

Needs more cats.

**Comment by ehelms** [comment]
A cat driving a Forklift?

**Pull request merged**
