### PR TITLE
Refs #7990 - use longer timeout for package tests

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by stbenjam** [comment]
Is 120 enough? If its pulling all the centos and katello metadata too maybe we should disable all the repos except the ones in redhat.repo?

**Comment by jlsherrill** [comment]
It should have that all downloaded and cached, but no harm in bumping to 5
minutes?

**Comment by stbenjam** [comment]
Hmm, ok, I thought maybe the 120 was needed because the cache was cleared, 30 seconds isn't enough for the local repo? Slow box?

Anyway, ACK from me

**Comment by mccun934** [comment]
ACK from me as well

**Comment by jlsherrill** [comment]
@stbenjam my guess is that http://projects.theforeman.org/issues/12375  may be partly to blame.  Last night one of the 2 bats tests (el6) did pass, previously neither were passing so my guess is that its taking slightly longer than 30 seconds, and looking at the logs that seems like what is happening.    We can always bump again if needed.

**Pull request merged**
