### PR TITLE
fix jenkins build that does not support insert_key

### PR DESCRIPTION
**Pull request by jlsherrill**
and seems to validate the ssh config

### CODE REVIEW

**Comment by ehelms** [comment]
Weird - I tested this exact case locally without issue.

**Comment by jlsherrill** [comment]
@ehelms maybe its using an even older version?  Or maybe something related to the rackspace plugin?  I'm not entirely sure, was just going by the error

**Comment by ehelms** [comment]
ACK

**Comment by jlsherrill** [comment]
reading:  https://github.com/edx/configuration/issues/1008  it does seem to be a very old version of vagrant that causes it.

**Pull request merged**
