### PR TITLE
Refs #7990 - install client repo rpm in addition to server

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Fixes Katello XL Pipeline leak

**Comment by ehelms** [comment]
What caused this sudden breakage?

**Comment by jlsherrill** [comment]
https://github.com/Katello/katello-deploy/pull/119 i assume.   the pipeline doesn't run over the weekend I don't think? so last night was the first run to catch it.

**Comment by ehelms** [comment]
Ohhh, I was thinking something broke it vs something new being added that requires it: makes perfect sense. I would have thought https://github.com/Katello/katello-packaging/blob/master/repos/katello-repos.spec#L61 implies that both repo files are deployed when installing katello-repos ?

**Comment by jlsherrill** [comment]
@ehelms hrmmmmm it should..... http://koji.katello.org/koji/rpminfo?rpmID=142267 

I'll investigate further

**Comment by jlsherrill** [comment]
@ehelms updated after further investigation

**Comment by ehelms** [comment]
ACK

**Pull request merged**
