### PR TITLE
Deploy plain Foreman

### PR DESCRIPTION
**Pull request by stbenjam**
Think this is useful to anyone else? I've been using it in my Katello-on-Foreman testing.

### CODE REVIEW

**Comment by ehelms** [comment]
I had something similar to this for a bit via the 'plugin' method, but having it properly here makes just about as much sense to me. Might be time to re-factor this file/break it out a bit soon. I'll test it sometime today.

**Comment by stbenjam** [comment]
I tested centos6 and it's fine, but I had odd problems with the ruby193 SCL repo on centos 7, but that happened even on Katello install - any idea what's up with that? Maybe it was just something with my setup.

**Comment by ehelms** [comment]
What was the error? Was it related to fetching the SCL file itself, like a 404?

**Comment by ehelms** [comment]
I think if you just rebased EL7 would work with @jlsherrill changes to how we handle the SCL.

**Comment by ehelms** [comment]
I think you need to account for the local case -- where I have katello-deploy/katello-installer as the script will attempt to run './bin/foreman-installer' and then fail.

**Comment by ehelms** [comment]
@stbenjam do you want to update this for the new structure?

**Comment by ehelms** [comment]
@stbenjam bump

**Comment by ehelms** [comment]
Replacement for this, given the re-factorings, https://github.com/Katello/katello-deploy/pull/174

**Comment by stbenjam** [comment]
Thanks @ehelms for taking this over!

**Pull request closed without merging**
