### PR TITLE
change bats content test to new hosts options

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
@zjhuntin does this look correct based on your recent changes?

**Comment by ekohl** [comment]
Does this only work on development versions or also on existing releases? Is that even a relevant question for this repo?

**Comment by ehelms** [comment]
Right now we only run our bats regularly for nightly tests, we have used it for pipeline testing releases before, and, at least for 3.0, this should work still.

**Comment by jlsherrill** [comment]
That said we did branch this repo at katello-2.4, maybe we should start doing that for every release.

**Comment by zjhuntin** [comment]
Yes, that does look correct!

**Pull request merged**
